# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.contrib.table_block.blocks

try:
    import wagtail.core.blocks as wc_blocks
    import wagtail.core.fields as wc_fields
    import wagtail.embeds.blocks as we_blocks
    import wagtail.images.blocks as wi_blocks
except ImportError:
    import wagtail.wagtailcore.blocks as wc_blocks
    import wagtail.wagtailcore.fields as wc_fields
    import wagtail.wagtailembeds.blocks as we_blocks
    import wagtail.wagtailimages.blocks as wi_blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wc_fields.StreamField((('heading', wc_blocks.TextBlock(icon='title', template='wagtailcontentstream/blocks/heading.html')), ('paragraph', wc_blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], icon='pilcrow')), ('image', wc_blocks.StructBlock((('image', wi_blocks.ImageChooserBlock()), ('caption', wc_blocks.TextBlock(required=False))))), ('embed', we_blocks.EmbedBlock(icon='media')), ('table', wagtail.contrib.table_block.blocks.TableBlock(icon='table')), ('code', wc_blocks.StructBlock((('language', wc_blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('http', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')])), ('code', wc_blocks.TextBlock())), icon='code'))), blank=True)),
                ('excerpt', wc_fields.RichTextField(blank=True, help_text='An short excerpt or abstract about the content.', null=True)),
            ],
            options={
                'verbose_name': 'Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SitePost',
            fields=[
                ('sitepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peregrine.SitePage')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time of the post.')),
                ('authors', models.ManyToManyField(blank=True, help_text='The authors of the post.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
            },
            bases=('peregrine.sitepage',),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='header_image',
            field=models.ForeignKey(blank=True, help_text='A featured image that will appear in the site theme header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
